### ISSUE TITLE
Doesn't work with inline partials

### ISSUE THREAD

**Issue by lzilioli** [pcardune/handlebars-loader#106]
If I try to require the following handlebars template using this loader, I get an error:

```
{{#*inline "toAttributes"}}
    {{#each this}}
        {{@key}}="{{this}}"
    {{/each}}
{{/inline}}

{{> toAttributes}}
```

The relevant stack from the error:

```
ERROR in ./public/pantry/page/index.hbs
Module build failed: Error: Partial 'toAttributes' not found
    at tryExtension (/Users/lzilioli/Projects/member-profile/node_modules/handlebars-loader/index.js:236:34)
    at /Users/lzilioli/Projects/member-profile/node_modules/handlebars-loader/index.js:246:11
    at next (/Users/lzilioli/Projects/member-profile/node_modules/handlebars-loader/index.js:189:20)
    at /Users/lzilioli/Projects/member-profile/node_modules/handlebars-loader/index.js:205:20
```

**Comment by lzilioli** [comment]
I suspect this has to do with the fact that the handlebars.JavascriptCompiler is invoking nameLookup for these inline partials, but haven't had a chance to debug further. @pcardune do you have any input here?

**Comment by mAAdhaTTah** [comment]
I got this working by providing empty default content:

```
{{#> toAttributes}}
{{/toAttributes}}
```

**Comment by mAAdhaTTah** [comment]
I stand corrected. The above trick works when the inline partial is defined in a separate file from where it's referenced.

**Comment by rafde** [comment]
I had to remove creating the error instance [here](https://github.com/pcardune/handlebars-loader/blob/master/index.js#L241-L242).
It shouldn't error out if it can't find the partial, it should when running the code. I'd submit a PR but there is stuff in the contrib I don't feel like doing so I'll do it later when I get more time.

**Comment by michaeldzjap** [comment]
I'm running into the same problem here. Would be nice if this could be fixed.

**Comment by EstherAF** [comment]
+1, I would like to use inline partials in the same file too.

**Comment by minkyu-yi** [comment]
As a workaround, use the `transform-loader` + `hbsfy`.

```js
        loaders: [
            {
                test: /\.hbs$/,
                exclude: /(node_modules|bower_components)/,
                loader: 'transform?hbsfy'
            },
            //.....
        ]
```

**Comment by skrolikowski** [comment]
Here's another workaround, add your inline partial name (e.g. toAttributes ) to the the _ignorePartials_ query:

```
loaders: [
    {
        test: /\.html$/,
        loader: 'handlebars-loader',
        query: {
            ignorePartials: [ 'toAttributes' ],
        }
    },
    //...
]
```

**Comment by sualko** [comment]
@pcardune can you look into this?

@skrolikowski your workaround works quite fine. Thanks.

**Comment by pcardune** [comment]
@sualko I don't have time to debug this right now, but if someone wants to submit a PR with a fix, I'd be more than happy to review/merge/release it.

**Comment by andreyvolokitin** [comment]
So this is a bug and not just unimplemented feature? Because Inline Partials and Decorators were two major features of Handlebars 4 and handlebars-loader docs say: 

> Handlebars 4 now supported

**Comment by KovalenkoStas** [comment]
@lzilioli and @pcardune this one should be closed because issue already resolve in https://github.com/pcardune/handlebars-loader/commit/a8a9773824710d8e774a7388a10602bd10430bad ! in Jan 21, 2018 .

**Comment by inkas** [comment]
@the-stas This still seems to be failing with webpack 4.44.2 and handlebars-loader 1.7.1 Would really love to be able to use inline partials.

**Comment by the-stas** [comment]
@inkas works fine for webpack 4.41.5 and handlebars-loader 1.7.1 , even works with webpack 5.9.0 and handlebars-loader 1.7.1

**Comment by inkas** [comment]
@the-stas 

My webpack handlebars-loader config looks like this
```
{
    test: /\.(hbs|handlebars)$/,
    loader: 'handlebars-loader',
    options: {
        partialDirs: [
            path.resolve(__dirname, 'src/templates/partials')
        ],
        helperDirs: [
            path.resolve(__dirname, 'src/assets/js/handlebars/helpers'),
            path.resolve(__dirname, 'src/templates/block-helpers')
        ],
    },
}
```
src/templates/partials/wrapper.hbs
```
<h2>{{> MyInlinePartial }}</h2>
```

src/templates/views/employees/index.hbs
```
{{#>wrapper}}
    {{#*inline "MyInlinePartial" }}
        Some text
    {{/inline}}
{{/wrapper}}
```

Error
```
ERROR in ./src/templates/partials/wrapper.hbs
Module build failed (from ./node_modules/handlebars-loader/index.js):
Error: Partial './MyInlinePartial' not found
    at tryExtension (C:\xampp\htdocs\project\node_modules\handlebars-loader\index.js:291:27)
    at C:\xampp\htdocs\project\node_modules\handlebars-loader\index.js:299:11
    at next (C:\xampp\htdocs\project\node_modules\handlebars-loader\index.js:241:20)
    at C:\xampp\htdocs\project\node_modules\handlebars-loader\index.js:257:20
    at C:\xampp\htdocs\project\node_modules\enhanced-resolve\lib\Resolver.js:213:14
    at C:\xampp\htdocs\project\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\xampp\htdocs\project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\xampp\htdocs\project\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
    at C:\xampp\htdocs\project\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\xampp\htdocs\project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
 @ ./src/templates/views/employees/index.hbs 16:41-78
 @ ./node_modules/html-webpack-plugin/lib/loader.js!./src/templates/views/employees/index.js
```

Am I doing something wrong?

**Comment by the-stas** [comment]
@inkas inline partial can be used only within the file where it define. In your case it can be used inly on `src/templates/views/employees/index.hbs` and probably it's definition can not be placed inside extend hbs syntax (but I'm not sure, haven't did that and do not check).

**Comment by inkas** [comment]
It seems to be working if I invoke the inline partial as a partial block.

src/templates/partials/wrapper.hbs
```
<h2>
  {{#> MyInlinePartial }}
    {{!-- MyInlinePartial content will be printed here --}}
  {{/MyInlinePartial}}
</h2>
```

**Comment by AmadeusK525** [comment]
Thanks @inkas, this is what got it working for me. It's a shame this wasn't properly fixed.
