### ISSUE TITLE
How to give it a context?

### ISSUE THREAD

**Issue by Milewski** [pcardune/handlebars-loader#117]
i was expecting something like this

```
{
   test: /\.handlebars$/,
   loader: 'handlebars-loader',
   options: {
      context: { world: "world" }
   }
}
```
then on my .handlebars file

```
Hello {{ world }} <-- outputs only "Hello ", no error... no hints... no clues...
```

Edit..

my current solution... which doesn't feels very right.. but works... is the following

./helpers/data.js

```
module.exports = function (key) {
    return require('../../../../context.json')[key];
}
```

index.handlebars

```
{{#each ( data 'features' ) }}
   <div class="feature">
      <h1>{{ feature }}</h1>
      <p>{{ description }}</p>
   </div>
{{/each }}
```

as you see im limited to the first level on my context.json i could build however a dot marked fn to grab deep nested object... but thats sounds too trouble if i have array in the way... also with pure handlebars this is so simple i think i might just have missed something on the documentation...

**Comment by pcardune** [comment]
When you require a handlebars file, a function which renders the template is returned. That function takes context as a parameter:


handlebars template:
```hbs
Hello {{world}}
```

usage in javascript:
```js
var myTemplate = require('./myTemplate.handlebars');
var result = myTemplate({world: "foo"});
```

**Comment by Milewski** [comment]
but this will return me a string.. in javascript side.. which i could possibly append to the dom.. however. im using this handlebars to generate a final output to be piped thought webpack `HtmlWebpackPlugin`.

so for example

```js
{
   test: /\.handlebars$/,
   loader: 'handlebars-loader',
   query: {
      inlineRequires: '/(images|videos)/',
      context: **'I NEED THIS'**, // <-- it would be lovely to have this 'global' context here...
      helperDirs: [
         path.join(__dirname, 'source/assets/views/helpers')
      ],
      partialDirs: [
         path.join(__dirname, 'source/assets/views/partials')
      ]
   }
},

....

new HtmlWebpackPlugin({
    filename: 'index.html',
    template: 'assets/views/index.handlebars',
})
```

so.. basically i need to give the context thought the webpack config itself...

**Comment by mAAdhaTTah** [comment]
You may need something more like this: https://github.com/sagold/handlebars-webpack-plugin

**Comment by Milewski** [comment]
yeah . i could.. but the problem with that is my other entry-points has ... hash names... which i wont know until it gets compiled... the advantage of using the HtmlWebpackPlugin is that it will get inserted automatically

**Comment by mAAdhaTTah** [comment]
Unfortunately, the handlebars loader won't help you here because a webpack loader (vs. plugin) simply can't do what you're asking.

**Comment by bfung** [comment]
A possible solution mentioned here; https://github.com/pcardune/handlebars-loader/issues/126#issuecomment-292943971
