### ISSUE TITLE
Images from template data

### ISSUE THREAD

**Issue by DirkWolthuis** [pcardune/handlebars-loader#120]
Hi guys, 

I have a problem getting images into my dist folder. I read issue #37 but I can't seem to get images form the template data to work properly. So long story short: 

If I have the following inside a template:
```
<img src="./../../assets/icons/hambuger_menu.svg" class="menu-btn ACTION_open_menu" alt="menu icoon">
```

It works fine and the svg get copied into the dist folder. 

But when using something like this:
```
<div class="boat-img bg-img-fill" style="background-image: url('{{img}}')">
```
or 
```
<img src="{{abr}}" alt="">
```
The images are not copied to the dist folder. 

I'm using the following webpackconfig file:

```
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin');
import {generateWebpackProxy} from './webpack.devsever.proxy'

module.exports = {
    devServer: {
        port: 8080,
        proxy: generateWebpackProxy(),
        //host: '192.168.178.20'
    },
    entry: './app/index.js',
    plugins: [new HtmlWebpackPlugin({
        template: 'app/templates/index.hbs', 
        
    })],
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /(node_modules|bower_components)/,
                loader: 'babel-loader',
                query: {
                    presets: ['es2015']
                }
            },
            {
                test: /\.hbs$/, 
                loader: "handlebars-loader",
                exclude: 'node_modules',
                query: {
                    partialDirs: [
                        path.join(__dirname, 'app', 'templates', 'partials')
                    ],
                    inlineRequires: '/assets/'
                }
            },
            
            {
                test: /\.(sass|scss)$/,
                use: [
                    'style-loader',
                    'css-loader',
                    'sass-loader',
                ]
                
            }, 
            { 
                test: /\.(jpe?g|png|gif|svg)$/i, 
                use: [ "file-loader?name=assets/[name].[ext]" ] 
            },
            
        ]
        
    },
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist'),
        publicPath: '/'
    }
};
```

**Comment by DirkWolthuis** [comment]
Okay so there were two bugs that made it not work for me. For future ref: you need to `require()` images inside the data files. It will import the image and place it in the dist folder.

**Comment by icesman** [comment]
@DirkWolthuis  I import the image  in the data files but it still doesn't work.
Webpack actually get it placed in the dist folder but it doesn't show normally.

**Comment by sideshowlol** [comment]
How about the parsing of srcset image links when using img srcset in a hbs template file? I can't find a way to get links within a srcset to be recognised.

Using inlineRequires solved the problem with regular "img src" links, but it doesn't help with any srcset links I have. 

Any thoughts on how to set up a test in my webpack.config? I currently have this:

```
{
        test: /\.hbs$/i,
        use: [
          {
            loader: "handlebars-loader",
            options: {
              inlineRequires: "/assets/images/",
              helperDirs: path.join(__dirname, "../src/assets/js/helpers"),
            },
          },
        ],
      },
```

I'm thinking of trying the preprocessor option in the html-loader for my next attempt to solve the problem with srcset image links which will mean not using the handlebars-loader at all.
