### ISSUE TITLE
Not compiling when updating partials

### ISSUE THREAD

**Issue by asotog** [pcardune/handlebars-loader#134]
To make it work need to re run `webpack-dev-server --port 9000 --host 0.0.0.0;` again, this issue started when updated handlebars and webpack version not sure what happens, please see this screenshot for versions:

<img width="355" alt="screen shot 2017-05-04 at 9 09 14 am" src="https://cloud.githubusercontent.com/assets/813023/25710487/9b742b8e-30a9-11e7-822e-3b898c8afb06.png">

**Comment by asotog** [comment]
UPDATE: reverted to 0.1.1 its working now, can you please provide feedback on what happened or if new version needs another flag in configuration ?

**Comment by mAAdhaTTah** [comment]
This repo is for the loader, not the plugin.

**Comment by asotog** [comment]
thanks didnt notice that :(, moving to plugin repo
