### ISSUE TITLE
is it possible to specify the default context directly from the loader?

### ISSUE THREAD

**Issue by nickaversano** [pcardune/handlebars-loader#138]
If I wanted to do something like this:
```javascript
{
  test: /\.html$/,
  loader: 'handlebars',
  query: {
    context: { meta: { title: 'hey' } }
  }
}
```
such that when html is loaded, it gets `context` as the current handlebars context. how would I accomplish something like this?

**Comment by mAAdhaTTah** [comment]
You're probably looking for for the Handlebars plugin. The loader exports a function you call in your code.

**Comment by nickaversano** [comment]
I got this working with the `HtmlWebpackPlugin` like so:
```
plugins: [
new HtmlWebpackPlugin({
  templateContent: function(templateParams, compilation, callback) {
    let source = fs.readFileSync('src/index.html', 'utf8')
    return Handlebars.compile(source)(context)
  }
})
]
```
