### ISSUE TITLE
Loader fails on Webpack 4

### ISSUE THREAD

**Issue by craigjennings11** [pcardune/handlebars-loader#155]
According to the Webpack 4 migration guide, `this.options` in the loaderContext was deprecated in v3 and is now removed in v4 (https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202). When I upgraded to webpack v4 and tried to build, I received this error:

> Module build failed: TypeError: Cannot read property 'handlebarsLoader' of undefined
>   at getLoaderConfig (C:\Github\agent\node_modules\handlebars-loader\index.js:24:37)
>   at Object.module.exports (C:\Github\agent\node_modules\handlebars-loader\index.js:32:15)

Seems like this code is no longer valid for v4

```js
function getLoaderConfig(loaderContext) {
  var query = loaderUtils.getOptions(loaderContext) || {};
  var configKey = query.config || 'handlebarsLoader';
  var config = loaderContext.options[configKey] || {}; /* This errors now */
  delete query.config;
  return assign({}, config, query);
}
```

**Comment by jamesalways** [comment]
+1 Thanks!

**Comment by craigjennings11** [comment]
Looks like this might be addressed via https://github.com/pcardune/handlebars-loader/pull/153

**Comment by jamesalways** [comment]
Hi!

Temporally use our fork: yarn upgrade handlebars-loader@github:Waavi/handlebars-loader

**Comment by frediana** [comment]
Hi, we successfully tested handlebars-loader@github:Waavi/handlebars-loader from @jamesalways on our project.

I think would be great to have this PR merged and have handlebars-loader to support webpack 4!

Thanks

**Comment by zGrav** [comment]
Check #153 .

Waavi fixed it, I made a PR to readd a specific line of code that handles issues with modules such as thread-loader and handlebars-loader :)

**Comment by pcardune** [comment]
This should be working now.
