### ISSUE TITLE
When is the release of this package for webpack > 4

### ISSUE THREAD

**Issue by rahulrkr08** [pcardune/handlebars-loader#158]
When I am trying to install this package, I am not getting latest updates for webpack > 4.0. when will be the release of this package available in NPM repository ?

**Comment by ccbikai** [comment]
+1 

now, I use `npm i https://github.com/pcardune/handlebars-loader.git`

**Comment by frediana** [comment]
+1 when could we expect this module to be publish? We need it in our project in order to complete webpack 4 migration, Thank!

**Comment by pcardune** [comment]
This has now been released. Thanks for your patience!
