### ISSUE TITLE
How to configure options of handlebars-loader for Webpack 4?

### ISSUE THREAD

**Issue by boris-jarkowicz** [pcardune/handlebars-loader#161]
I'm currently migrating a project to webpack 4 and so far so good.

I've updated `handlebars-loader` to 1.7.0 and am facing the problem that my options apparently cannot be fetched, because i'm getting errors that my helpers and partials cannot be found.

My current implementation looks like this:
```
new webpack.LoaderOptionsPlugin({
    test: /\.hbs$/,
    options: {
        handlebarsLoader: {
           knownHelpersOnly: false,
           inlineRequires: /\/assets\/(:?images|audio|video)\//ig,
           helperDirs: [path.join(__dirname, '/lib/hbs-helpers')],
           partialDirs: [path.join(PATHS.TEMPLATES, 'partials')],
         },
    },
})
```
I guess using `LoaderOptionsPlugin` is the problem here.
What do i need to do to make it work or where can i find some example that shows the right way?

Thanks in advance :)

**Comment by dennisblack666** [comment]
For me it works with that type of config:

```
module.exports = { 
    module: {
        rules: [{
            test: /\.hbs.html/,
            use: [{
                loader: 'handlebars-loader',
                options: {
                    helperDirs: [__dirname + "/../handlebars/helpers"]
                }
            }]
        }]
    },   
    plugins: [       
        new webpack.LoaderOptionsPlugin({
            options: {
                handlebarsLoader: {}
            }
        })
    ]
};
```

When i dont use **LoaderOptionsPlugin** in my config, i also getting erros on the build.

**Comment by boris-jarkowicz** [comment]
Hey! thanks for your reply, i've managed already to get it working writing the following code:
```
module: {
    rules: [{
        test: /\.hbs$/,
        loader: 'handlebars-loader',
        options: {
            knownHelpersOnly: false,
            inlineRequires: /\/assets\/(:?images|audio|video)\//ig,
            helperDirs: [path.join(__dirname, '/lib/hbs-helpers')],
            partialDirs: [path.join(PATHS.TEMPLATES, 'partials')],
        },
    }
    ... other configuration stuff
    ],
},
```

**Comment by vijayakumar-psg587** [comment]
@boris-jarkowicz  Sorry to post in an old thread, but does this configuration create the hbs files after webpack build, I too went with the same configuration but after the webpack build I do not see any hbs files created?. I went through the main.js file created after the build and I do not see the template being created.  For some strange reason I am unable to run the main,js file as well. So please let me know if the hbs template would still be visible after the build?

THis is my webpack.dev.js

```
module.exports = {
  entry: './src/server.ts',
  mode: 'development',
  target: 'node',
  output: {
    path: path.join(__dirname, 'dist'),
    filename: '[name].js'
  },
  resolve: {
    extensions: ['.ts', '.js'],
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: [
          'ts-loader',
        ]
      },
      {
        test: /\.handlebars$/,
        loader: 'handlebars-loader',
        options: {
            knownHelpersOnly: false,
            inlineRequires: /\/assets\/(:?images|audio|video)\//ig,
            partialDirs: [path.join(__dirname, './src/views/email/partials')],
        },
    }
    ]
   
  },
  externals: [ nodeExternals() ],
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV':'"development"'
    }),
    new CleanWebpackPlugin({
    }),
    new webpack.EvalSourceMapDevToolPlugin({
      filename: '[name].map.js'
    })
  ]
}
```

And this is the folder strcuture where the template and partials are placed

> src
> --app
> ----modules
> ------...
> ------...
> --views
> ----email
> ------template.handlebars
> ------email.body.handlebars
> ------partials
> --------header.handlebars
> --------footer.handlebars
