### ISSUE TITLE
layout template multiple pages

### ISSUE THREAD

**Issue by gregorvoinov** [pcardune/handlebars-loader#164]
Hi,

I started to use  handlebars-loader and it works well, but now i want to create some more static sites. Is there an easy way, if I have a folder with files like index.hbs, about.hbs,... to create all files at once? Because at the moment I have only one entry point and because of that i get only one file rendered.

cheers ;)

**Comment by milewski** [comment]
use `webpack-html-plugin` multiple times, one for each file you wanna create...

**Comment by gregorvoinov** [comment]
yeah found already a solution

    const pages =  fs
        .readdirSync(path.resolve(__dirname, 'src/hbs/pages'))
        .filter(fileName => fileName.endsWith('.hbs'));

    plugins: [
        ...pages.map(page => new HtmlWebpackPlugin({
            template: 'hbs/pages/'+page,
                filename: filename: page.split(".")[0]+".html",
                templateParameters: require('./src/data/bundle.json')
            }))
    ]
