### ISSUE TITLE
Audit issue; package async; affected versions < 3.2.2 

### ISSUE THREAD

**Issue by wiesesascha** [pcardune/handlebars-loader#206]
In npm audit the package 'async' is considered a high risk due to prototype pollution. 

**Solution** is an update to version >= 3.2.2

See:
https://github.com/advisories/GHSA-fwr7-v2mv-hh25

**Comment by wiesesascha** [comment]
Made a PR #207 for this. 
NOT tested in deep so far :)

**Comment by sebsauer90** [comment]
Can we expect a new version for this? :)

**Comment by attenzione** [comment]
@pcardune can you assist? the last version was released 3 years ago and we need at least some patches. Thanks

**Comment by wiesesascha** [comment]
> @pcardune can you assist? the last version was released 3 years ago and we need at least some patches. Thanks

In case you really need to pass auditing you can solve this by [overwriting](https://www.npmjs.com/package/overwrite) the version number of async.

Another way would be an own fork where you can update the affected package by your own.

**Comment by pcardune** [comment]
Thanks for the ping @attenzione. I'll get a release out shortly.

**Comment by pcardune** [comment]
This has been fixed in in 1.7.2
