### ISSUE TITLE
Custom helpers / custom handlebars library

### ISSUE THREAD

**Issue by iby** [pcardune/handlebars-loader#3]
Alan, thanks for putting this out. I remember seeing somewhere that custom helpers are not supported, but can't find that information now. Is this true?

Also, if I understand correctly, the loader pulls it's own copy of handlebars library and it kind of sucks that there's no way to use the dependency from the project. Is there any way to add that option into configuration? I'm not a guru on the subject, but something like configuring an alias in the main webpack.config and passing it to the loader to use instead of the default library would be fantastic.

**Comment by sbnajardhane** [comment]
@altano commented on Mar 17 2014
Regarding this comment.
I have around 15 helper functions in my handlebar template, may be they will increase in future. So can I write all those functions in single handlebarHelper.js file and export from there.
I have tried to export helper function like modular jQuery pattern, but it didn't work.
handlebarHelper.js

    module.exports = (function() {

	    var helper1 = function(data) {
	        return "helper1"
	    };

	    var helper2 = function(data) {
	        return "helper2";
	    };
	    return {
	        helper1: helper1,
	        helper2: helper2
	    };
	})();


 Any thoughts??
thanks
