### ISSUE TITLE
Need maintainer

### ISSUE THREAD

**Issue by altano** [pcardune/handlebars-loader#79]
Paging everyone with an open pull request and a few others: 

@diurnalist @larryhe @pcardune @ianmetcalf @kt0 @simenb @divmain @jcreamer898 @duncanbeevers @ericmatthys @rakeshmenon

This project could use a maintainer.  I've poured dozens of hours into maintaining this despite only ever having used the code myself in an extremely minimal side-project.  I'm kind of swamped and don't really want to devote my time to this project right now.

If anyone has enough passion around it it would be great if someone would take over ownership of it.  There are 8 open Pull Requests and a bunch of issues but I don't believe this loader really requires that much work so it wouldn't be too big a deal, just more than I'm willing to put in right now.

**Comment by SimenB** [comment]
I'll volunteer, but I'm quitting my current job (and thus using this loader) in three months, so it may  actually only be a stop-gap solution.
But if no one else steps forward I can do it, at least for the forseeable future. :smile: We've used this loader for over a year, and we're very happy with it, so maintaining it even after I personally don't use it shouldn't be much of a chore

**Comment by kt0** [comment]
@altano 
I don't have enough time for maintenance, but will contribute if I get spare time.

BTW, in a few months we will move away from handlebars and use react instead for our project.

**Comment by larryhe** [comment]
Hi @altano , thanks for your time on this great project. and this is how open source works and every one of us in this community would definitely to contribute our efforts. since there are so many pull requests over there. could you somebody merge them and have a new release first? @SimenB , Thanks for your volunteer. Any ideas on this?

**Comment by pcardune** [comment]
Now that I'm back from various travels, I would be happy to step in as maintainer. What's the best way to do this? Just transfer the repo to my account so all the issues/pull requests get moved over? And presumably give me access to the published library on npm?

**Comment by pcardune** [comment]
@altano I'm ready to take over if you want to give me access. See my message above.

**Comment by altano** [comment]
Thanks everyone who offered to help.  Sorry for the delay in response, I've been away from home for huge chunks of time this year.

If @pcardune is willing to be a full maintainer I'm just going to transfer ownership to him and he can solicit help from the rest of you as he'd like.

@pcardune: thanks for stepping up.  You now have co-ownership of the npm repository and I've given you push rights to the github repository.  Please see to:

- [ ] Making sure you have all the rights needed to maintain this package.
- [ ] Modifying the `README` and `package.json` to reflect that there is a new maintainer.

And of course let me know if there's anything I can do.

**Comment by pcardune** [comment]
Great, thanks. Will get to work on everything a little later today!

**Comment by pcardune** [comment]
@altano Would it be alright if you transferred ownership to my account so it appears under /pcardune/handlebars-loader? I'd like to add a few build tools like travis-ci to auto run unit tests and code coverage for pull requests, and I can only do that on repositories under my own account.

**Comment by altano** [comment]
@pcardune no problem but you'll have to delete/rename your fork of the repo first.  I got the error `pcardune/handlebars-loader already exists` when i tried just now.

**Comment by pcardune** [comment]
@altano ok, try again. Just deleted my fork.

**Comment by altano** [comment]
@pcardune tried again, it successfully sent a request to you to do the transfer.

**Comment by pcardune** [comment]
For folks following along on this thread, I would appreciate some help reviewing the backlog of outstanding pull requests and issues. If you have time, please leave a +1 comment on any pull request you've reviewed to indicate that the changes look good to you. I'll do my best to avoid merging breaking changes, but would appreciate a second pair of eyes.  Thanks!

**Comment by pcardune** [comment]
release 1.2.0 is out. Get it while it's hot.

**Comment by altano** [comment]
The flurry of activity is fun to watch.  Thanks for all the hard work, Paul.
