### ISSUE TITLE
Define partials at build-time/render-time

### ISSUE THREAD

**Issue by mAAdhaTTah** [pcardune/handlebars-loader#95]
For compatibility reasons, I have a project using some bundled modules with mustache templates, where the partial "path" doesn't exactly match the module name/location. We were using Hogan.js and providing those partials with their compiled templates at rendertime, rather than compiletime. We're looking at upgrading the Mustache templates to Handlebars, but the old templates fail to compile with `handlebars-loader` because it fails to resolve the templates.

Is there any way to tell the loader to use a particular template for a given partial? Or failing that, ensure it doesn't error out and continue to provide those partials at rendertime?

**Comment by lzilioli** [comment]
I have a similar issue where we have a custom webpack resolver for module paths so the name of a module or handlebars partial call does not map to anything on the filesystem. Instead we resolve this using our own logic and I need to hook that logic into the handlebars-loader, or provide a static mapping of partial names => location on the filesystem.

**Comment by pcardune** [comment]
I'm happy to review a pull request. Can't say when I'll get around to addressing this problem myself.

**Comment by mAAdhaTTah** [comment]
@pcardune I'd be happy to look into working on this, but I'm not that familiar with webpack transforms. If you have any guidance you can provide, I can work on an initial implementation for you to review.
